name: Build SWU

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        push: false
        context: .
        build-args: version=${{ github.sha }}
        outputs: type=local,dest=./build/dist
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rinkhals:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rinkhals:buildcache,mode=max

    - name: Upload artifact for K2P, K3
      uses: actions/upload-artifact@v4
      with:
        name: update-k2p-k3
        compression-level: 0
        path: |
          build/dist/*-k2p-k3.swu

    - name: Upload artifact for KS1
      uses: actions/upload-artifact@v4
      with:
        name: update-ks1
        compression-level: 0
        path: |
          build/dist/*-ks1.swu
